/*
HOST_GL.H

The PS4 host's OpenGL ES layer: Piglet's ES 2 entry points (hostreal_*,
generated by tools/ps4_gl_host.py into host_gl_real.h), the ES 3 emulation
over them (host_gl_es2.c, es2_*) and the GLSL translation (host_shader.c).
*/

#ifndef __HALO_PS4_HOST_GL_H
#define __HALO_PS4_HOST_GL_H

#include "host.h"

#include <GLES2/gl2.h>
#include <GLES2/gl2ext.h>

/* the OpenGL ES 3 enumerants the renderer passes that gl2.h lacks */
#define ES3_READ_FRAMEBUFFER 0x8ca8
#define ES3_DRAW_FRAMEBUFFER 0x8ca9
#define ES3_READ_FRAMEBUFFER_BINDING 0x8caa
#define ES3_DEPTH_STENCIL_ATTACHMENT 0x821a
#define ES3_DEPTH_STENCIL 0x84f9
#define ES3_UNSIGNED_INT_24_8 0x84fa
#define ES3_DEPTH24_STENCIL8 0x88f0
#define ES3_RGBA8 0x8058
#define ES3_RGB8 0x8051
#define ES3_BGRA_EXT 0x80e1
#define ES3_TEXTURE_3D 0x806f
#define ES3_TEXTURE_2D_ARRAY 0x8c1a
#define ES3_TEXTURE_WRAP_R 0x8072
#define ES3_TEXTURE_MIN_LOD 0x813a
#define ES3_TEXTURE_MAX_LOD 0x813b
#define ES3_TEXTURE_BASE_LEVEL 0x813c
#define ES3_TEXTURE_MAX_LEVEL 0x813d
#define ES3_TEXTURE_LOD_BIAS 0x8501
#define ES3_TEXTURE_COMPARE_MODE 0x884c
#define ES3_TEXTURE_COMPARE_FUNC 0x884d
#define ES3_TEXTURE_SWIZZLE_R 0x8e42
#define ES3_TEXTURE_SWIZZLE_G 0x8e43
#define ES3_TEXTURE_SWIZZLE_B 0x8e44
#define ES3_TEXTURE_SWIZZLE_A 0x8e45
#define ES3_TEXTURE_BORDER_COLOR 0x1004
#define ES3_CLAMP_TO_BORDER 0x812d
#define ES3_TEXTURE_MAX_ANISOTROPY 0x84fe
#define ES3_RED 0x1903
#define ES3_GREEN 0x1904
#define ES3_BLUE 0x1905
#define ES3_ALPHA 0x1906
#define ES3_MAJOR_VERSION 0x821b
#define ES3_MINOR_VERSION 0x821c
#define ES3_NUM_EXTENSIONS 0x821d
#define ES3_MAX_FRAGMENT_ATOMIC_COUNTERS 0x92d6
#define ES3_COPY_READ_BUFFER 0x8f36
#define ES3_COPY_WRITE_BUFFER 0x8f37
#define ES3_PIXEL_PACK_BUFFER 0x88eb
#define ES3_PIXEL_UNPACK_BUFFER 0x88ec
#define ES3_UNIFORM_BUFFER 0x8a11
#define ES3_TRANSFORM_FEEDBACK_BUFFER 0x8c8e
#define ES3_ATOMIC_COUNTER_BUFFER 0x92c0
#define ES3_QUERY_BUFFER 0x9192
#define ES3_ANY_SAMPLES_PASSED 0x8c2f
#define ES3_ANY_SAMPLES_PASSED_CONSERVATIVE 0x8d6a
#define ES3_SAMPLES_PASSED 0x8914
#define ES3_QUERY_RESULT 0x8866
#define ES3_QUERY_RESULT_AVAILABLE 0x8867
#define ES3_PRIMITIVE_RESTART_FIXED_INDEX 0x8d69
#define ES3_RASTERIZER_DISCARD 0x8c89
#define ES3_PROGRAM_POINT_SIZE 0x8642
#define ES3_UNPACK_ROW_LENGTH 0x0cf2
#define ES3_UNPACK_SKIP_ROWS 0x0cf3
#define ES3_UNPACK_SKIP_PIXELS 0x0cf4
#define ES3_UNPACK_IMAGE_HEIGHT 0x806e
#define ES3_UNPACK_SKIP_IMAGES 0x806d
#define ES3_PACK_ROW_LENGTH 0x0d02
#define ES3_PACK_SKIP_ROWS 0x0d03
#define ES3_PACK_SKIP_PIXELS 0x0d04
#define ES3_COMPRESSED_RGBA_S3TC_DXT1_EXT 0x83f1
#define ES3_COMPRESSED_RGBA_S3TC_DXT3_EXT 0x83f2
#define ES3_COMPRESSED_RGBA_S3TC_DXT5_EXT 0x83f3
#define ES3_COMPRESSED_RGB_S3TC_DXT1_EXT 0x83f0

#include "host_gl_real.h"

/* what the driver offers (host_gl.c) */
struct host_gl_capabilities
{
	int npot;               /* GL_OES_texture_npot: mipmaps and repeat */
	int bgra;               /* GL_EXT_texture_format_BGRA8888 */
	int packed_depth_stencil; /* GL_OES_packed_depth_stencil */
	int depth24;            /* GL_OES_depth24 */
	int anisotropy;         /* GL_EXT_texture_filter_anisotropic */
	int s3tc;
	int occlusion_query;    /* GL_EXT_occlusion_query_boolean */
	int fbo_render_mipmap;  /* GL_OES_fbo_render_mipmap */
	int discard_framebuffer; /* GL_EXT_discard_framebuffer */
	int element_index_uint; /* GL_OES_element_index_uint */
	GLint max_vertex_attributes;
	GLint max_vertex_uniform_vectors;
	GLint max_fragment_uniform_vectors;
	GLint max_texture_units;
	GLint max_texture_size;
};

extern struct host_gl_capabilities host_gl_capabilities;

int host_gl_driver_has_extension(const char *name);

/* the guest's imports (port/android/guest/runtime/guest_host.h) */
void host_gl_get_string(uint32_t name, int index, char *buffer, uint32_t size);
int host_gl_has_extension(const char *name);
uint32_t host_gl_read_buffer_word(uint32_t buffer, uint32_t offset);
void host_gl_buffer_write(uint32_t target, uint32_t offset, uint32_t size, const void *data);
void host_gl_fence_frame(uint32_t slot);
void host_gl_wait_frame(uint32_t slot);
void *host_gl_proc(const char *name);

/* host_gl_es2.c */
void es2_initialize(void);
void es2_log_statistics(void);

#endif
