#!/usr/bin/env python3
"""Generate the PS4 host's OpenGL ES entry points for the guest.

The guest calls the OpenGL ES 3 functions in port/linux/src/gl.h's Android
list through imports named hostgl_<function> (tools/android_gl_stubs.py
writes the guest side). The PS4 has OpenGL ES 2 only (Piglet), so the host
implements each import either by calling Piglet's function directly or, for
functions that ES 2 lacks or whose ES 3 behaviour differs, through the
emulation in port/ps4/host/host_gl_es2.c, which defines es2_<function> for
each name in EMULATED below.

This also writes the table of Piglet's own entry points (hostreal_<function>
for every function in GLES2/gl2.h), resolved once the context exists
(host_gl_load_real), which the emulation calls.

Usage: ps4_gl_host.py gl.h gl32.h gl2ext.h output.c
"""

import re
import sys

# OpenGL ES 3 functions ES 2 lacks, and ES 2 functions whose ES 3 use by the
# renderer needs translating (formats, framebuffer targets, shaders, sampler
# objects applied at draw time)
EMULATED = {
    # ES 3 only
    "glBeginQuery", "glEndQuery", "glGenQueries", "glGetQueryObjectuiv",
    "glBindBufferBase", "glBindBufferRange",
    "glGenSamplers", "glBindSampler", "glSamplerParameteri", "glSamplerParameterf", "glSamplerParameterfv",
    "glGenVertexArrays", "glBindVertexArray",
    "glBlitFramebuffer", "glCopyImageSubData", "glDrawBuffers", "glReadBuffer", "glInvalidateFramebuffer",
    "glTexImage3D", "glCompressedTexImage3D",
    "glDrawElementsBaseVertex", "glVertexAttribIPointer", "glVertexAttribI4ui",
    # ES 2 functions used with ES 3 arguments
    "glGetIntegerv", "glEnable", "glDisable", "glPixelStorei", "glReadPixels",
    "glGenTextures", "glDeleteTextures", "glBindTexture", "glActiveTexture",
    "glTexImage2D", "glTexSubImage2D", "glCompressedTexImage2D", "glGenerateMipmap",
    "glTexParameteri", "glTexParameteriv", "glTexParameterf", "glTexParameterfv",
    "glDeleteFramebuffers", "glBindFramebuffer", "glFramebufferTexture2D", "glCheckFramebufferStatus",
    "glVertexAttribPointer",
    "glDrawArrays", "glDrawElements",
    "glShaderSource", "glAttachShader", "glLinkProgram", "glUseProgram",
    "glBindBuffer", "glDeleteBuffers", "glBufferData", "glBufferSubData",
    "glEnableVertexAttribArray", "glDisableVertexAttribArray",
}

# functions the guest reaches through host_gl_get_string rather than an import
NOT_IMPORTED = {"glGetString"}


def android_functions(gl_header):
    text = open(gl_header, encoding="utf-8").read()
    start = text.index("/* ANDROID_GL_FUNCTIONS_BEGIN */")
    end = text.index("/* ANDROID_GL_FUNCTIONS_END */")
    return re.findall(r"X\((\w+)\)", text[start:end])


def prototypes(*headers):
    result = {}
    pattern = re.compile(r"GL_APICALL\s+(.+?)\s*GL_APIENTRY\s+(\w+)\s*\((.*?)\);", re.S)
    for header in headers:
        text = open(header, encoding="utf-8").read()
        for ret, name, params in pattern.findall(text):
            params = " ".join(params.split())
            result.setdefault(name, (ret.strip(), params))
    return result


def es2_names(gl32):
    """The functions of OpenGL ES 2.0 (the part of gl32.h before ES 3.0)."""
    text = open(gl32, encoding="utf-8").read()
    start = text.index("#ifndef GL_ES_VERSION_2_0")
    end = text.index("#ifndef GL_ES_VERSION_3_0")
    return re.findall(r"GL_APICALL\s+.+?\s*GL_APIENTRY\s+(\w+)\s*\(", text[start:end], re.S)


def split_parameters(params):
    if params in ("void", ""):
        return []
    result = []
    for index, param in enumerate(params.split(",")):
        param = param.strip()
        m = re.match(r"(.*?)(\w+)\s*$", param)
        ptype = m.group(1).strip() if m and m.group(1).strip() else param
        result.append((ptype, f"a{index}"))
    return result


def main():
    gl_header, gl32, gl2ext, output = sys.argv[1:5]
    functions = [f for f in android_functions(gl_header) if f not in NOT_IMPORTED]
    protos = prototypes(gl32, gl2ext)
    es2 = es2_names(gl32)
    missing = [f for f in functions if f not in es2 and f not in EMULATED]
    if missing:
        raise SystemExit(f"OpenGL ES 3 functions without an emulation in host_gl_es2.c: {', '.join(missing)}")

    out = [
        "/* generated by tools/ps4_gl_host.py from port/linux/src/gl.h; do not edit */",
        '#include "host_gl.h"',
        "",
        "/* ---------- Piglet's OpenGL ES 2 entry points */",
        "",
    ]
    for name in es2:
        ret, params = protos[name]
        out.append(f"{ret} (GL_APIENTRY *hostreal_{name})({params});")
    out += [
        "",
        "static const struct { const char *name; void **pointer; } real_functions[] =",
        "{",
    ]
    out += [f'\t{{ "{name}", (void **)&hostreal_{name} }},' for name in es2]
    out += [
        "};",
        "",
        "int host_gl_load_real(void *(*get_proc_address)(const char *name))",
        "{",
        "\tunsigned long index;",
        "\tint missing = 0;",
        "",
        "\tfor (index = 0; index < sizeof(real_functions) / sizeof(real_functions[0]); index++)",
        "\t{",
        "\t\t*real_functions[index].pointer = get_proc_address(real_functions[index].name);",
        "\t\tif (!*real_functions[index].pointer)",
        "\t\t{",
        '\t\t\thost_logf(HOST_LOG_WARN, "gl: %s is missing", real_functions[index].name);',
        "\t\t\tmissing++;",
        "\t\t}",
        "\t}",
        "\treturn missing;",
        "}",
        "",
        "/* ---------- the guest's imports */",
        "",
    ]
    for name in functions:
        ret, params = protos[name]
        plist = split_parameters(params)
        decl = ", ".join(f"{t} {a}" for t, a in plist) or "void"
        args = ", ".join(a for _, a in plist)
        returns = ret != "void"
        out.append(f"{ret} hostgl_{name}({decl})")
        out.append("{")
        if name in EMULATED:
            out.append(f"\t{'return ' if returns else ''}es2_{name}({args});")
        else:
            out.append(f"\tif (!hostreal_{name})")
            out.append("\t{")
            out.append(f'\t\thost_gl_missing("{name}");')
            out.append(f"\t\treturn{' 0' if returns else ''};")
            out.append("\t}")
            out.append(f"\t{'return ' if returns else ''}hostreal_{name}({args});")
        out.append("}")
        out.append("")

    header = [
        "/* generated by tools/ps4_gl_host.py; do not edit */",
        "#ifndef __HOST_GL_REAL_H",
        "#define __HOST_GL_REAL_H",
        "",
    ]
    for name in es2:
        ret, params = protos[name]
        header.append(f"extern {ret} (GL_APIENTRY *hostreal_{name})({params});")
    header.append("")
    for name in sorted(EMULATED):
        if name not in protos:
            continue
        ret, params = protos[name]
        plist = split_parameters(params)
        decl = ", ".join(f"{t} {a}" for t, a in plist) or "void"
        header.append(f"{ret} es2_{name}({decl});")
    header += ["", "#endif", ""]

    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    with open(output.rsplit("/", 1)[0] + "/host_gl_real.h" if "/" in output else "host_gl_real.h", "w",
              encoding="utf-8") as f:
        f.write("\n".join(header))


if __name__ == "__main__":
    main()
