#!/usr/bin/env python3
"""Generate the PS4 guest image's host import stubs (x32).

The x86-64 counterpart of tools/android_imports.py: every function the guest
imports from the host (port/ps4/host_imports.list, plus the generated POSIX
and OpenGL ES lists) gets a stub in the image that jumps through the host's
64-bit function address in __host_import_table. The arguments are left
untouched in their registers: x32 and the host's x86-64 ABI pass them the
same way (port/ps4/include/halo_ps4_abi.h). The host fills in the table when
it loads the image (port/ps4/host/host_loader.c).

Usage: ps4_imports.py [--host-table table.c] output.s list...

With --host-table, also writes the host's name-to-function table for every
name in the lists. Unlike Android, the OpenGL ES imports are part of it: the
PS4 host implements each hostgl_ function itself (host_gl_dispatch.c, made by
tools/ps4_gl_host.py), emulating OpenGL ES 3 on Piglet's OpenGL ES 2.
"""

import sys


def read_names(lists):
    names = []
    for path in lists:
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line and line not in names:
                names.append(line)
    return names


def host_symbol(name):
    # hostposix_<name> imports port/linux/src/posix.h's posix_<name>
    if name.startswith("hostposix_"):
        return "posix_" + name[len("hostposix_"):]
    return name


def main():
    arguments = sys.argv[1:]
    host_table = None
    if arguments and arguments[0] == "--host-table":
        host_table = arguments[1]
        arguments = arguments[2:]
    if len(arguments) < 2:
        raise SystemExit(__doc__)
    output, lists = arguments[0], arguments[1:]
    names = read_names(lists)

    out = ["/* generated by tools/ps4_imports.py; do not edit */", "\t.text"]
    for index, name in enumerate(names):
        out += [
            f"\t.globl {name}",
            f"\t.type {name},@function",
            "\t.p2align 3",
            f"{name}:",
            f"\tjmpq *__host_import_table+{index * 8}(%rip)",
        ]
    out += [
        "\t.section .rodata",
        "\t.globl __host_import_names",
        "__host_import_names:",
    ]
    out += [f'\t.asciz "{name}"' for name in names]
    out += [
        "\t.p2align 2",
        "\t.globl __host_import_count",
        "__host_import_count:",
        f"\t.long {len(names)}",
        "\t.data",
        "\t.p2align 3",
        "\t.globl __host_import_table",
        "__host_import_table:",
        f"\t.zero {max(len(names), 1) * 8}",
        '\t.section .note.GNU-stack,"",@progbits',
    ]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    if host_table:
        table = ["/* generated by tools/ps4_imports.py; do not edit */",
                 "#include <string.h>", ""]
        table += [f"extern void {host_symbol(n)}(void);" for n in names]
        table += ["", "static const struct { const char *name; void *function; } imports[] =", "{"]
        table += [f'\t{{ "{n}", (void *){host_symbol(n)} }},' for n in names]
        table += ["};", "",
                  "void *host_resolve_import(const char *name)",
                  "{",
                  "\tunsigned long index;",
                  "",
                  "\tfor (index = 0; index < sizeof(imports) / sizeof(imports[0]); index++)",
                  "\t{",
                  "\t\tif (!strcmp(imports[index].name, name))",
                  "\t\t\treturn imports[index].function;",
                  "\t}",
                  "\treturn NULL;",
                  "}", ""]
        with open(host_table, "w", encoding="utf-8") as f:
            f.write("\n".join(table))


if __name__ == "__main__":
    main()
