#!/usr/bin/env python3
"""Generate the PS4 system library stubs eboot.bin links against.

The console's system modules (libkernel, libScePad, ...) are resolved at run
time by the dynamic linker through NIDs, which create-fself computes from
symbol names. At link time LLD only needs shared objects that define the
names, with the right DT_SONAME (create-fself derives the library and
module names from it: libScePad.so -> library and module "libScePad").

This writes such stubs from idc/ps4libdoc, a public database of the
modules' exported symbol names (JSON per module; tools/ps4_setup_toolchain.sh
clones the 5.05 branch). Every named symbol of the requested library becomes
a global function in libNAME.so; the stubs contain no code from the console.

Usage: ps4_stub_libs.py [--cc CLANG] [--ld LD.LLD] PS4LIBDOC_DIR OUTPUT_DIR LIBRARY...
e.g.   ps4_stub_libs.py /opt/oo/ps4libdoc build/ps4/stubs libkernel libScePad
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def library_index(root: Path):
    """library name -> set of symbol names, over every module in the tree"""
    index = {}
    for path in sorted(root.rglob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except (OSError, ValueError):
            continue
        for module in data.get("modules", []):
            for library in module.get("libraries", []):
                names = index.setdefault(library["name"], set())
                for symbol in library.get("symbols", []):
                    name = symbol.get("name")
                    if name and IDENTIFIER.match(name):
                        names.add(name)
    return index


def write_stub(name: str, symbols, output: Path, cc: str, ld: str) -> Path:
    source = output / f"{name}.stub.s"
    obj = output / f"{name}.stub.o"
    shared = output / f"{name}.so"
    lines = [f"# {name}: {len(symbols)} symbols from ps4libdoc (generated by tools/ps4_stub_libs.py)", "\t.text"]
    for symbol in sorted(symbols):
        lines += [f"\t.globl {symbol}", f"\t.type {symbol},@function", f"{symbol}:", "\tret"]
    source.write_text("\n".join(lines) + "\n", encoding="utf-8")
    subprocess.run([cc, "--target=x86_64-pc-freebsd12-elf", "-c", str(source), "-o", str(obj)], check=True)
    subprocess.run([ld, "-m", "elf_x86_64", "-shared", "-soname", f"{name}.so", "-o", str(shared), str(obj)],
                   check=True)
    obj.unlink()
    return shared


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--cc", default="clang")
    parser.add_argument("--ld", default="ld.lld")
    parser.add_argument("ps4libdoc", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("libraries", nargs="+")
    args = parser.parse_args()

    index = library_index(args.ps4libdoc)
    if not index:
        print(f"ps4_stub_libs: no ps4libdoc JSON under {args.ps4libdoc}", file=sys.stderr)
        return 1
    args.output.mkdir(parents=True, exist_ok=True)
    for name in args.libraries:
        symbols = index.get(name)
        if not symbols:
            print(f"ps4_stub_libs: ps4libdoc has no library {name}", file=sys.stderr)
            return 1
        path = write_stub(name, symbols, args.output, args.cc, args.ld)
        print(f"ps4_stub_libs: {path} ({len(symbols)} symbols)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
